### ISSUE TITLE
Custom badges text

### ISSUE THREAD

**Issue by floatdrop** [harness/harness#141]
This is more like feature request - is it handy to pass text to `badge` handle and generate images like ![](http://img.shields.io/badge/deploy-success-brightgreen.png) or ![](http://img.shields.io/badge/tests-failing-red.png) instead of standart ![](https://raw.github.com/drone/drone/master/cmd/droned/assets/img/build_failing.png)?

**Comment by scpeters** [comment]
Sorry if this is the wrong place to ask, but will this be deployed to the open source drone.io service?
