### ISSUE TITLE
/var/cache/drone is used, but not created

### ISSUE THREAD

**Issue by kirs** [harness/harness#180]
Now `/var/cache/drone` is not created automatically.

We also cannot just put `mkdir -p /var/cache/drone` in Makefile because it requires sudo access.

**Comment by Jdesk** [comment]
is there an answer to this??? I'm going through this now in 2015 a year later :-)

**Comment by Jdesk** [comment]
recursive caching 50 levels deep - my build will work but not until run number 51.

**Comment by bradrydzewski** [comment]
yes, caching was re-implemented in 0.4 and is documented here: http://readme.drone.io/docs/build/cache.html

> recursive caching 50 levels deep - my build will work but not until run number 51.

not sure I understand, perhaps you can clarify this statement

**Comment by Jdesk** [comment]
I figured it out my friend :-) - Made a few config changes - FYI drone rocks!!!! I hated it 24 hours ago and now i am in love.   If there is anything at all I can do for you guys let me know.

**Comment by Jdesk** [comment]
It is going to make my life so much easier - I already created a drone server and gitlab ce server (yes I know gitlab has ci but yours is 10 times better.  I just need a private repo :-)
