### ISSUE TITLE
Builds hanging when fetching a repository

### ISSUE THREAD

**Issue by mnutt** [harness/harness#206]
I'm having an issue where my drone builds are occasionally hanging while fetching a repository.  The docker container is still running afterwards, but the build is stuck in the 'Started' state forever.  I'm wondering if maybe it's related to https://github.com/dotcloud/docker/issues/1474 ?

Full drone logs: https://gist.github.com/mnutt/f422b2d84808f0e983bd (another PR came in halfway through the build so it's a bit convoluted)

**Comment by amirhj** [comment]
I faced the same problem and the git command returns timeout while cloning from local gitlab server.
I changed DNS resolution address in host machine and now in docker build it works fine
