### ISSUE TITLE
Page constantly refreshes during build

### ISSUE THREAD

**Issue by michaelmior** [harness/harness#21]
If a build is still in progress and I visit the status page, my browser continually refreshes every second until the build is done.

**Comment by johnrengelman** [comment]
@bradrydzewski I think Rancher had this same issue and resolved it by implementing support for ProxyProtocol which ELB supports - Is this any option for Drone?
http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html

**Comment by bradrydzewski** [comment]
0.4 branch uses [server sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) which is uses pure http and does not require a protocol upgrade like websockets. It will need to be tested, however, this may solve the issue with ELB.

**Comment by johnrengelman** [comment]
hmmmm....I'm running the `drone/drone:latest` build from yesterday (9/13) and I was not getting streamed events in the web view when doing a build behind an AWS elb. 
I see there is a 0.4 branch, should I be building that and using it instead?

**Comment by bradrydzewski** [comment]
0.4 is not stable, however, it isn't far from being released either. I wouldn't recommend using it quite yet, but since release is not far off we aren't making major changes to the stable channel
