### ISSUE TITLE
-log.file option doesn't seem to work, custom log file not created.

### ISSUE THREAD

**Issue by rosstimson** [harness/harness#231]
I've tried running `droned` using the following options:

```
droned -datasource=/var/lib/drone/drone.sqlite -log.debug=true -log.file=/var/log/droned.log -port=:443 -sslcert=/etc/pki/tls/certs/example.com.crt -sslkey=/etc/pki/tls/private/example.com.key
```

I've also tried setting these values in the startup script (`/etc/init/drone.conf`) too.  However, the logfile that I specify never gets created.  I am running `droned` as root user and I've tried creating the logfile and `chmod`ing to 777 in preparation just to rule out permissions issues.

On a separate note, I did find the default logfile (`/var/log/upstart/drone.log`) and noticed that not everything was timestamped which might be worth considering in the future.

**Comment by ginkoob** [comment]
@bradrydzewski  did you consider glog (github.com/golang/glog) ? It's really emabrassing to not be able to log stuff to a file. How am I supposed to inspect the logs if there is no log?

**Comment by bradrydzewski** [comment]
@ginkoob as mentioned in the other thread, you are using an outdated tutorial, and un-official image, and an unsupported operating system. Logging is supported in the official installation in `/var/log/upstart/drone.log` (on Ubuntu) and `/var/log/drone.log` on systems using `init.d`
