### ISSUE TITLE
Not able to build with gradlew

### ISSUE THREAD

**Issue by JacobASeverson** [harness/harness#256]
Trying to build a Java project with the gradle wrapper. My build script is simply:
./gradlew build

Error I get is:
OpenJDK Runtime Environment (IcedTea 2.3.10) (7u25-2.3.10-1ubuntu0.12.04.2)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)
$ ./gradlew build
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by Blackbaud-CraigPemberton** [comment]
This solved a problem for me. Thank you Jacob.

**Comment by aisensiy** [comment]
I got the same issue again, but I already add the jar file into repository.
