### ISSUE TITLE
How can I backup my repositories?

### ISSUE THREAD

**Issue by matheusoreis** [harness/harness#3436]
I work in a company that doesn't use any versioning services because they are web based, I discovered Gitness these days and I need to make backups of project files to an internal server, how can I get the folders where the repository files are?

I made a docker-compose.yaml so I could use gitness.

![image](https://github.com/harness/gitness/assets/47448206/551e6066-68fe-4244-b70e-b38c9bbfd465)

I tried using the docker cp command but it did basically what docker-compose.yaml did.

I'm new to docker.

**Comment by htcosta** [comment]
You should be able to backup your data by copying the contents of “/home/gitness/data” in your host (not the container.

Please read : 
https://docs.gitness.com/administration/configuration
https://docs.docker.com/storage/bind-mounts/

I am not sure if gitness already has this functionality on the UI/CLI, but and export or import field under the Administration tab / CLI flag could be added to add this extra functionality, it’s a easy implementation.

**Comment by matheusoreis** [comment]
It's not there, I want to have access to the source code of the projects, is that possible?

**Comment by 34code** [comment]
I've been backing up `/home/gitness` nightly.. Now its the moment of truth to recover from backup.. gonna test today and report back if above worked.. I'm particularly curious since my backup medium (hetzner storage box) does not support symlinks for some reason.. 

```
mv: cannot create symbolic link '/root/backup/08-02-2024/repos/f1/in/chorootih83xv8es9ix26r2c74pq4w4b2x9cx3.git/hooks/pre-receive': Operation not supported
```

**Comment by 34code** [comment]
I can confirm it works! Just needed to restart container after moving back up sqlite db and repos to /home/gitness!
