### ISSUE TITLE
Feature Request: Support for Displaying the Webhook Execution List

### ISSUE THREAD

**Issue by ysicing** [harness/harness#3533]
requesting support for displaying a list of webhook executions within our application. Currently, users can manage webhooks by adding or removing them from their accounts. However, there is no feature to view which specific webhooks have been triggered, when they were triggered, and any associated metadata such as the request payload.

**Comment by johannesHarness** [comment]
Hey @ysicing, thanks for taking the time to submit this feature request 🚀 
Webhook executions is something we've been planning to add and is actively tracked.
As of now, the data itself is already available via REST API (full UI support will follow in the future).

To get the list of executions for a specific webhook, you can make the following curl call:
``` shell
curl 'http://localhost:3000/api/v1/repos/{Space Identifier}%2F{Repo Identifier}/webhooks/{Webhook Identifier}/executions' \
  -H 'Authorization: Bearer {API Token}'
``` 
> Note: you can pipe it into `jq` to format the json.

**Comment by hitesharinga** [comment]
Hey @ysicing, We have released this in the latest harness tag. https://hub.docker.com/r/harness/harness/tags

Thanks
