### ISSUE TITLE
Trigger build only on specific branches

### ISSUE THREAD

**Issue by Andrew8xx8** [harness/harness#355]
We like your service; it is easy-to-use one. 

We would like to have the opportunity to build only specific branches, for instance, master or staging.

I have looked into the code but have not found such opportunity, I could find only #291, in which there is the possibility to define the brunch only for plugin.

Do you consider making this functionality more common?

Maybe we can help you to realize this feature.

**Comment by fommil** [comment]
does this take glob patterns?

I'm finding that it is not possible to restrict to `master` and `pull/*` on github repositories, so there is no way to ignore work-in-progress branches.

**Comment by dbendy** [comment]
@fommil: have you found an answer to your question?  I am searching for the same thing.

**Comment by donny-dont** [comment]
@dbendy we have multiple support channels referenced in the README and this issue is almost a year old.

The documentation for this is at http://readme.drone.io/usage/skipping-builds/. If something is missing then feel free to bring it up on gitter.
