### ISSUE TITLE
Production Deployment

### ISSUE THREAD

**Issue by p5** [harness/harness#3564]
Hi Harness team - congrats on v3.0!

I would love to start hosting Harness Open Source (love the rebrand btw!) for my lab, however I would prefer to do so in a "production-ready" manor.  

There's a few features which are either missing or undocumented, and it would be great to hear if they are planned on being public, or only accessible within your managed offering for large enterprises.

These features include:
- Highly available deployments of Harness (2-3 node clusters)
- Distributed pipeline runners (running CI pipelines on other VMs, allows easier multi-arch builds)
- SSO authentication

These features would bring the platform closer in-line with other open source alternatives, such as GitLab.

Absolutely love what you all are doing, and look forward to whatever comes next.

**Comment by dewan-ahmed** [comment]
Hi @p5 we're glad you like the product! All the features you've requested are currently available in our commercial offering at app.harness.io, and we encourage you to check it out to see what we offer.

Our goal with Harness Open Source is to provide small teams with an end-to-end DevOps platform that delivers the same great user experience as our commercial offering, before they are ready for an enterprise-grade platform. Features like SSO and HA are planned to remain part of the enterprise offering.

Thanks again for your interest and we're excited to see what you build with Harness Open Source!

**Comment by lifeofguenter** [comment]
Having distributed CI runners for sure is even important for hobby projects given the current industry standard.

Not having HA or SSO are expected.
