### ISSUE TITLE
Rename GITNESS_URL_BASE to HARNESS_URL_BASE

### ISSUE THREAD

**Issue by Lock128** [harness/harness#3565]
In order to pass a custom dns name and other config you need to pass environment variables ... they are here

https://github.com/harness/harness/blob/077256b69c16ebe26ae7c85284ef6b3101bd3c80/types/config.go#L57

and they still refer to GITNESS instead of HARNESS

I suggest to correct that ;)

**Comment by pwolf-harness** [comment]
Thanks. Yes. We have an Epic open to remove all references over time. We want to phase these changes in to minimize risk.
