### ISSUE TITLE
Google Auth Login and signup flow

### ISSUE THREAD

**Issue by basav22** [harness/harness#3579]
Hello

Can you please add Google Auth to signin and sign up flow?
It will be easier for user migration and added security.

**Comment by pwolf-harness** [comment]
Thanks for your feedback and idea. I have created a new enhancement request here:  https://ideas.harness.io/feature-request/p/support-openid-providers

**Comment by pwolf-harness** [comment]
Please refer to the enhancement request link for future updates here.
