### ISSUE TITLE
Chart renders volumeClaimTemplates for Deployment

### ISSUE THREAD

**Issue by zc-devs** [harness/harness#3580]
Rendering Helm chart with default values I get [gitness.yaml](https://github.com/user-attachments/files/17680615/gitness.yaml.txt).
As you can see there is `kind: Deployment` with `volumeClaimTemplates` which is invalid for Deployments.
So, make it `Statefulset` or remove `volumeClaimTemplates`. I've tested the latter and it works.

https://github.com/harness/harness/blob/main/charts/gitness/values.yaml#L59-L62
https://github.com/harness/harness/blob/main/charts/gitness/templates/deployment.yaml#L95-L114

**Comment by abhinav-harness** [comment]
we merged it https://github.com/harness/harness/pull/3590
