### ISSUE TITLE
internal err occurred ?? it there any detail ?

### ISSUE THREAD

**Issue by mouuii** [harness/harness#3582]
![1731143369529](https://github.com/user-attachments/assets/537e9327-1ad5-4f67-a5fb-7b4c147836a4)

**Comment by mouuii** [comment]
the doc is too little for pipeline

**Comment by pwolf-harness** [comment]
Does this error continue to show up, @mouuii ?  If you click on "Inspect" and bring up the browser console does it show any more details?
