### ISSUE TITLE
Is the front-end visual UI similar to the one shown in the figure, which replaces the.drone.yml code, open source?

### ISSUE THREAD

**Issue by SoftwareKing** [harness/harness#3595]
<img width="1514" alt="image" src="https://github.com/user-attachments/assets/340c08bf-87db-440c-8779-a59917dd076d">

**Comment by SoftwareKing** [comment]
@tnhu @Ibmurai @p404 @alexohneander

**Comment by pwolf-harness** [comment]
Thanks for reaching out. No, the pipeline studio editor shown in the screenshot above is not currently open source.
