### ISSUE TITLE
Gitspace Container Network missing

### ISSUE THREAD

**Issue by NyroCodes** [harness/harness#3602]
I get an error, when I try to create an gitspace.

`177 13.12.2024 13:36:22  fatal: unable to access 'http://harness:3000/git/Test/Test.git/': Could not resolve host: harness`

I set GITNESS_URL_CONTAINER and GITNESS_CI_CONTAINER_NETWORKS which works for the pipeline.

So I suspect, that the container network isn't added to the gitspace container.

**Comment by dhruv-harness** [comment]
Hi @NyroCodes 

Can you please share the configuration which you used to run the harness container? eg the docker run command or the docker compose file?

**Comment by dhruv-harness** [comment]
@NyroCodes In the error message, the clone url is `http://harness:3000/git/Test/Test.git/` but in the compose config I see that url has been commented. 
For Harness' repos, the gitspaces use the `GITNESS_URL_CONTAINER` property to determine the clone url. Gitspace DO NOT support any docker network other than the default as of now ie the `bridge` network.

**Comment by NyroCodes** [comment]
Yeah I know that I commented out the version that isn't working.

So gitspace doesn't support the same feature as the ci containers. Good to know
