### ISSUE TITLE
unable to clone private repo

### ISSUE THREAD

**Issue by amos6224** [harness/harness#371]
Cloning into '/var/cache/drone/src/github.com/repo/private'...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

Hey guys i am having a hard time to clone a private repo with drone during deploy. however public works fine

**Comment by log0ymxm** [comment]
@amos6224 What was the docker issue?

**Comment by mtanzi** [comment]
Hi @bradrydzewski I am experiencing a similar problem, when drone try to deploy my repository it has the right key but it complains when it try to fetch the git submodules:

```
ERROR: Repository not found.
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:xxx/my_other_repo.git' into submodule path 'my_other_repo' failed
```
I checked the public key and they are correct for both the main repo and the submodule repo 

Do you have any idea why it doesn't find the repository?

**Comment by MhdAli** [comment]
@bradrydzewski what is the line to uncomment to debug this kind of issues?
