### ISSUE TITLE
Bundle & private git repo for gem

### ISSUE THREAD

**Issue by iRyusa** [harness/harness#387]
Hello,

It's kinda related to #371 I guess. I have a gem on my Gemfile that reference a private git repo. But looks like I can't...

Here's the log:

``` sh
$ bundle install --without darwin --deployment
Fetching gem metadata from https://rubygems.org/......
Fetching gem metadata from https://rubygems.org/..
Fetching git@github.com:diramode/YYYYYYYY.git
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
ERROR: Repository not found.
fatal: The remote end hung up unexpectedly
Git error: command `git clone 'git@github.com:diramode/YYYYYY.git'
"/var/cache/drone/src/github.com/diramode/XXXXX/vendor/bundle/ruby/2.0.0/cache/bundler/git/YYYYYYYY-2c9787449e6b9fabb47c6158c859494b1829942f"
--bare --no-hardlinks` in directory
/var/cache/drone/src/github.com/diramode/XXXX has failed.
```

Note that drone pulls the application without any problems:

``` sh
$ git clone --depth=50 --recursive --branch=check-email git@github.com:diramode/XXXXXXX.git /var/cache/drone/src/github.com/diramode/XXXXXXX
Cloning into '/var/cache/drone/src/github.com/diramode/XXXXXXX'...
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
$ git checkout -qf c78ddd675d5ecb9d4e8121220cca1d9013f53e3f
```

I tried to cat `.ssh` but looks empty 

``` sh
$ cat ~/.ssh/id_rsa.pub
cat: /home/ubuntu/.ssh/id_rsa.pub: No such file or directory
```

Here's my  `.drone.yml`

``` yml
image: ruby2.0.0
script:
  - psql -c 'create database test;' -U postgres -h 127.0.0.1
  - cp config/database.drone.yml config/database.yml
  - bundle install --without darwin --deployment
  - RAILS_ENV=test bundle exec rake db:create db:schema:load db:migrate
  - RAILS_ENV=test bundle exec rspec
services:
  - postgres
```

Did I miss something on the documentation ?

Thanks for any help !

**Comment by fjguzman** [comment]
I see a problem here if we have a lot of applications that use the same private repositories, we can end adding a drone key per application we can build inside drone. 

What about the user could add a public key on the repositories settings inside drone. So the organization/user can create a drone key and paste to be used from any drone build (could be configured per repository on drone but the same key for all the repositories)

**Comment by bradrydzewski** [comment]
@fjguzman as of Drone 0.4 we add a `.netrc` file to the build environment (private repositories only) which is used to automatically authenticate and clone private repositories from with `git+https`. This eliminates the need to manage ssh keys. You just need to alter your dependency files (ie package.json, Gemfile, etc) to use the `https` url instead of the `git+ssh` url
