### ISSUE TITLE
GitHub Service Hook

### ISSUE THREAD

**Issue by Zolmeister** [harness/harness#446]
Travis CI has a custom GitHub Service hook, which allows it to do this:

![](http://i.imgur.com/qvkAdmg.png)

Is this feature coming to Drone.io? (or is it there and I can't find it?)

**Comment by Zolmeister** [comment]
@bradrydzewski Any updates on this?
http://beta.drone.io/ doesn't seem to be quite right...

**Comment by bradrydzewski** [comment]
beta.drone.io service was shutdown. Now using test.drone.io. Looks like digital ocean re-allocated the IP address so I need to revoke the DNS entry :)  Good catch!

**Comment by bradrydzewski** [comment]
but there are no updates because, as far as I know, there are no issues. You can see examples of this working her with the latest pull request we received: https://github.com/drone/drone/pull/963
