### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by nils-werner** [harness/harness#526]
Whenever I try to run `sudo drone status`, `repos` or `whoami` I get a weird error message:

```
invalid character '<' looking for beginning of value
```

I am using the latest `.deb`, so I guess it is version 17d773fac

**Comment by vermanotes** [comment]
For me it got fixed after sync-up drone CLI and drone Server version. I was using higher CLI version. Later I down-grade the CLI and it worked.
