### ISSUE TITLE
Customize timeout before killing job?

### ISSUE THREAD

**Issue by cboettig** [harness/harness#554]
It appears that Drone is killing my very long-running tests.  As a major incentive for using drone running on my own server was the ability to run CI test suites that would take more than 50 minutes to execute, it's rather disappointing to see Drone kill them anyway (if that is indeed what is going on -- the log is not very informative so I suppose other errors may be possible, all I see is `/usr/local/bin/drone: line 42:   321 Killed`)

Do we / could we have some way to toggle the time a job is allowed to run before being killed?

**Comment by thunderstorm99** [comment]
May it be that this is open again? I can't seem to find any field for this value on the website.

**Comment by bradrydzewski** [comment]
the field exists, but you need to be a system administrator to view it. See the users section of the administration guide.

**Comment by thunderstorm99** [comment]
That actually did it. Sorry for the question. Thanks for the super fast help!
