### ISSUE TITLE
Cannot add BitBucket repo in 0.3

### ISSUE THREAD

**Issue by jloh** [harness/harness#652]
For some reason I can't add a BitBucket repo at all in 0.3. It pulls my repos fine and syncs them locally, but it doesn't actually add any hooks on BitBuckets side.

When I click activate the spinning wheel runs, then disappears and no errors get printed out to `/var/log/upstart/drone.log` but I do get a 500 error upon adding it in the developer console.

```
POST https://drone.mooash.com/api/repos/bitbucket.org/Mooash/Testing 500 (Internal Server Error) angular.js:7991
(anonymous function) angular.js:7991
C angular.js:7813f angular.js:7547
C angular.js:10943
C angular.js:10943
(anonymous function) angular.js:11029
h.$eval angular.js:11949
h.$digest angular.js:11775
h.$apply angular.js:12055
(anonymous function) angular.js:17833
(anonymous function) angular.js:2612
q angular.js:309
Zc.c angular.js:2611
```

At first I thought it was due to my repo being called something with spaces so `%20` characters get printed in the URL.

**Comment by rafaelbeckel** [comment]
Same issue here. Changing repo to lowercase didn't solve it.
