### ISSUE TITLE
Github OAuth redirect

### ISSUE THREAD

**Issue by prologic** [harness/harness#679]
Hi, Wasn't able to initially find a similar issue (if any); I've followed the installation instructions of Drone as per http://drone.readthedocs.org/en/latest/setup.html but when I try to link to my Github account I get teh following error message:

```
http://localhost:8080/api/auth/github.com?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=FqB4EbagQ2o
```

**Comment by Telmo** [comment]
neither are actually working for me.

with `http://mydrone.example.com/auth/login/github`
I get redirected to the login page with this URL
```
http://mydrone.example.com/login?error=redirect_uri_mismatch&error_description=The%2Bredirect_uri%2BMUST%2Bmatch%2Bthe%2Bregistered%2Bcallback%2BURL%2Bfor%2Bthis%2Bapplication.&error_uri=https:%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=MOJHRGH4ZZYP3FRRIG2G2NH3GC67WUWCRJJN3YWXSG25SPX2EPAQ%3D%3D%3D%3D```

with `http://mydrone.example.com/api/auth/github.com`
I get redirected to a blank page with the following URL
```
http://mydrone.example.com/api/auth/github.com?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=5MZHULRXL7IS3WR4TMVEDABMKUI2PEXI3KZCDK6HSPMF6HVUYK6A%3D%3D%3D%3D
```

I am following the documentation per [http://drone.readthedocs.org/en/latest/setup.html](http://drone.readthedocs.org/en/latest/setup.html) and [http://readme.drone.io/setup/config/github/](http://readme.drone.io/setup/config/github/)

**Comment by bradrydzewski** [comment]
@Telmo these are the correct docs:
http://readme.drone.io/setup/config/github/

The error message seems to indicate the authorization callback URL wasn't configured properly when the application was registered with GitHub:

> error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application

The authorization callback URL should look something like this, based on your example:

```
http://mydrone.example.com/api/auth/github.com
```

**Comment by ginkoob** [comment]
when I  try to login using my github account on  mydomain/login I'm redirected to github, I login and then I'm redirected to a blank page (mydomain.com:8080/api/auth/github.com?code=25533209db7e33eb58&state=som urlencoded) . If I inspect the response headers it seems I have http 400. How can I debug this ? It seems there is no log whatsoever. I"m running it from a docker container ( see https://www.digitalocean.com/community/tutorials/how-to-perform-continuous-integration-testing-with-drone-io-on-coreos-and-docker# )

**Comment by bradrydzewski** [comment]
@ginkoob that article references a very old version of Drone that is no longer supported, as well as an un-official image. Check readme.drone.io for official installation instructions on supported platforms
