### ISSUE TITLE
Prevent build concurrency?

### ISSUE THREAD

**Issue by darkpixel** [harness/harness#683]
Is there a way to prevent builds from occurring concurrently?
I have code that I need to test, but it can't be run at the same time.  Currently drone is building the master branch, and a merged hotfix branch at the same time, and develop appears to be queued (hotfix was merged into develop as well).  I've only ever seen drone run two builds at the same time, but is there a way to drop it to one for a project or the whole install?

**Comment by gertcuykens** [comment]
I need it! My jenkins setup that provides this feature saves me alot of headache when i get 100 callbacks from services telling me that data has changed asking to rebuild the same build. If i ask for  100 new builds Jenkins just add just add one in que waiting for the last one to finish.

**Comment by tonglil** [comment]
@gertcuykens this issue is from 2014, you may want to evaluate the latest Drone and chat with the community in gitter/stackoverflow/discourse if it doesn't satisfy your requirements. If we can confirm it is a feature request, then we can start a new issue to track that.

**Comment by gertcuykens** [comment]
Didn't get response yet https://stackoverflow.com/questions/45708815/prevent-build-concurrency-in-drone-ci I assume this feauture is not availeble yet in drone. I prefer reopening this issue to prevent scattering of related issues

**Comment by TekTimmy** [comment]
Hello, so I'm using drone to automatically deploy the develop / release branch after an pull request. For the case when 2 pull requests are merged at the same time it really makes sense to only keep the latest drone job and cancel all previous.

**Comment by bradrydzewski** [comment]
see https://discourse.drone.io/t/how-to-limit-build-concurrency-per-project/3500
