### ISSUE TITLE
"Service Timeout" with GitHub Enterprise

### ISSUE THREAD

**Issue by MitchK** [harness/harness#724]
Hi,

All my GitHub Enterprise web hook calls get a "Service Timeout":
![screen shot 2014-11-21 at 17 09 33](https://cloud.githubusercontent.com/assets/2472064/5145252/84775010-71a1-11e4-9b16-d12d95ea0b0a.png)

There is no error in `/var/log/upstart/drone.log`

Our internal GitHub Enterprise's SSL certificate is btw signed by an internal root certificate, not by a public one. Can this be an issue?

I've added the root certificate of the GitHub Enterprise instance to the Ubuntu key store of the Drone.io server. Is that enough? Does the Go application recognize the certificate? 

Thanks,
Michael

**Comment by Tebro** [comment]
I have this problem at the moment, was there any clear fix?

**Comment by olafurpg** [comment]
I experienced the same issue. FWIW, it was caused by the fact that the server running drone was only reachable from my internal network.
